
### Importar Arquivos e Bibliotecas

In [1]:
#importar bibliotecas
import pandas as pd
import pathlib
import win32com.client as win32

In [7]:
#importar arquivos
email_df = pd.read_excel(r'Bases de Dados\Emails.xlsx')
lojas_df = pd.read_csv(r'C:Bases de Dados\Lojas.csv', encoding='latin-1', sep=';')
vendas_df = pd.read_excel(r'Bases de Dados\Vendas.xlsx')
display(email_df)
display(lojas_df)
display(vendas_df)

                                Loja      Gerente                       E-mail
0                 Iguatemi Esplanada       Helena       helena+email@gmail.com
1               Shopping Midway Mall        Alice        alice+email@gmail.com
2                     Norte Shopping        Laura        laura+email@gmail.com
3        Shopping Iguatemi Fortaleza      Manuela      manuela+email@gmail.com
4           Shopping União de Osasco    Valentina    valentina+email@gmail.com
5         Shopping Center Interlagos       Sophia       sophia+email@gmail.com
6                     Rio Mar Recife     Isabella     isabella+email@gmail.com
7                  Salvador Shopping      Heloisa      heloisa+email@gmail.com
8         Rio Mar Shopping Fortaleza        Luiza        luiza+email@gmail.com
9   Shopping Center Leste Aricanduva        Julia        julia+email@gmail.com
10                 Ribeirão Shopping       Lorena       lorena+email@gmail.com
11                  Shopping Morumbi        Livia        livia+email@gmail.com
12         Parque Dom Pedro Shopping  Maria Luiza  maria luiza+email@gmail.com
13               Bourbon Shopping SP      Cecilia      cecilia+email@gmail.com
14       Palladium Shopping Curitiba         Eloa         eloa+email@gmail.com
15         Passei das Águas Shopping       Miguel       miguel+email@gmail.com
16        Center Shopping Uberlândia       Arthur       arthur+email@gmail.com
17                   Shopping Recife       Heitor       heitor+email@gmail.com
18               Shopping Vila Velha     Bernardo     bernardo+email@gmail.com
19                Shopping SP Market         Davi         davi+email@gmail.com
20                 Shopping Eldorado         Theo         theo+email@gmail.com
21               Shopping Ibirapuera      Lorenzo      lorenzo+email@gmail.com
22      Novo Shopping Ribeirão Preto      Gabriel      gabriel+email@gmail.com
23                 Iguatemi Campinas        Pedro        pedro+email@gmail.com
24                    Shopping Barra     Benjamin     benjamin+email@gmail.com
25                         Diretoria    Diretoria    diretoria+email@gmail.com

    ID Loja                              Loja
0         1                Iguatemi Esplanada
1         2              Shopping Midway Mall
2         3                    Norte Shopping
3         4       Shopping Iguatemi Fortaleza
4         5          Shopping União de Osasco
5         6        Shopping Center Interlagos
6         7                    Rio Mar Recife
7         8                 Salvador Shopping
8         9        Rio Mar Shopping Fortaleza
9        10  Shopping Center Leste Aricanduva
10       11                 Ribeirão Shopping
11       12                  Shopping Morumbi
12       13         Parque Dom Pedro Shopping
13       14               Bourbon Shopping SP
14       15       Palladium Shopping Curitiba
15       16         Passei das Águas Shopping
16       17        Center Shopping Uberlândia
17       18                   Shopping Recife
18       19               Shopping Vila Velha
19       20                Shopping SP Market
20       21                 Shopping Eldorado
21       22               Shopping Ibirapuera
22       23      Novo Shopping Ribeirão Preto
23       24                 Iguatemi Campinas
24       25                    Shopping Barra

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,1,Sapato Estampa,1,358,358
1,1,2019-01-01,1,Camiseta,2,180,360
2,1,2019-01-01,1,Sapato Xadrez,1,368,368
3,2,2019-01-02,3,Relógio,3,200,600
4,2,2019-01-02,3,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204
100995,69996,2019-12-26,17,Mochila,4,270,1080
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108
100998,69997,2019-12-26,11,Short Linho,2,133,266

### Criar uma Tabela para cada Loja e Definir o dia do Indicador

In [3]:
#adicionar nome da loja na tabela vendas
vendas_df = vendas_df.merge(lojas_df, on='ID Loja')
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Iguatemi Esplanada
1,1,2019-01-01,1,Camiseta,2,180,360,Iguatemi Esplanada
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Iguatemi Esplanada
3,21,2019-01-02,1,Camisa Gola V Listrado,2,116,232,Iguatemi Esplanada
4,34,2019-01-02,1,Sapato Listrado,1,363,363,Iguatemi Esplanada
...,...,...,...,...,...,...,...,...
100994,69846,2019-12-25,8,Short Estampa,2,96,192,Salvador Shopping
100995,69846,2019-12-25,8,Tênis Estampa,5,256,1280,Salvador Shopping
100996,69850,2019-12-25,8,Calça Estampa,4,177,708,Salvador Shopping
100997,69972,2019-12-26,8,Terno Liso,3,720,2160,Salvador Shopping
100998,69972,2019-12-26,8,Sapato Estampa,5,358,1790,Salvador Shopping

In [4]:
#criar uma tabela para cada loja
dic_lojas = {}
for loja in lojas_df['Loja']:
    dic_lojas[loja] = vendas_df.loc[vendas_df['Loja']==loja, :]
display(dic_lojas['Passei das Águas Shopping'])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
28491,10,2019-01-02,16,Camiseta Xadrez,2,200,400,Passei das Águas Shopping
28492,10,2019-01-02,16,Cueca Liso,1,69,69,Passei das Águas Shopping
28493,19,2019-01-02,16,Relógio Listrado,1,218,218,Passei das Águas Shopping
28494,19,2019-01-02,16,Calça Linho,2,211,422,Passei das Águas Shopping
28495,199,2019-01-02,16,Camiseta,2,180,360,Passei das Águas Shopping
...,...,...,...,...,...,...,...,...
32486,69745,2019-12-24,16,Camiseta,3,180,540,Passei das Águas Shopping
32487,69861,2019-12-25,16,Terno Linho,5,750,3750,Passei das Águas Shopping
32488,69861,2019-12-25,16,Camiseta Xadrez,2,200,400,Passei das Águas Shopping
32489,69937,2019-12-25,16,Sunga Xadrez,5,116,580,Passei das Águas Shopping
32490,69957,2019-12-25,16,Bermuda Estampa,1,169,169,Passei das Águas Shopping

In [5]:
#definir dia do indicador
dia_indicador = vendas_df['Data'].max()
print(dia_indicador)
print(f'{dia_indicador.day}/{dia_indicador.month}')

2019-12-26 00:00:00
26/12

### Salvar a planilha na pasta de backup

In [6]:
#criar pasta da loja dentro da pasta backup e verificar se a pasta já existe
caminho_backup = pathlib.Path(r'Backup Arquivos Lojas')
arquivos_pasta_backup = caminho_backup.iterdir()
lista_nomes_backup = [arquivo.name for arquivo in arquivos_pasta_backup]

for loja in dic_lojas:
    if loja not in lista_nomes_backup:
        nova_pasta = caminho_backup / loja
        nova_pasta.mkdir()

    #criar arquivo dentro da pasta de cada loja
    nome_arquivo = f'{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx'
    local_arquivo = caminho_backup / loja / nome_arquivo
    dic_lojas[loja].to_excel(local_arquivo)

### Calcular o indicador para 1 loja

In [7]:
#definição das metas
meta_faturamento_dia = 1000
meta_faturamento_ano = 1650000
meta_qtdeprodutos_dia = 4
meta_qtdeprodutos_ano = 120
meta_ticketmedio_dia = 500
meta_ticketmedio_ano = 500

In [10]:
mail = email_df.loc[email_df['Loja']==loja, 'E-mail'].values[0]
print(f'OnePage Dia {dia_indicador.day}/{dia_indicador.month} - Loja {loja}')

OnePage Dia 26/12 - Loja Passei das Águas Shopping

### Enviar por e-mail para o gerente (Outlook)

In [ ]:
for loja in dic_lojas:
    
    vendas_loja = dic_lojas[loja]
    vendas_loja_dia = vendas_loja.loc[vendas_loja['Data']==dia_indicador, :]
    
    loja = 'Passei das Águas Shopping'
    vendas_loja = dic_lojas[loja]
    vendas_loja_dia = vendas_loja.loc[vendas_loja['Data']==dia_indicador, :]

    #faturamento
    faturamento_ano = vendas_loja['Valor Final'].sum()
    faturamento_dia = vendas_loja_dia['Valor Final'].sum()

    #diversidade produtos
    qtdeprodutos_ano = len(vendas_loja['Produto'].unique())
    qtdeprodutos_dia = len(vendas_loja_dia['Produto'].unique())

    #ticket médio
    valor_venda = vendas_loja.groupby('Código Venda').sum()
    ticket_medio_ano = valor_venda['Valor Final'].mean()
    valor_venda_dia = vendas_loja_dia.groupby('Código Venda').sum()
    ticket_medio_dia = vendas_loja_dia['Valor Final'].mean()
    
    #enviar email
    outlook = win32.Dispatch('outlook.application')
    nome = email_df.loc[email_df['Loja']==loja, 'Gerente'].values[0]
    mail = outlook.CreateItem(0)
    mail.To = email_df.loc[email_df['Loja']==loja, 'E-mail'].values[0]
    mail.Subject = f'OnePage Dia {dia_indicador.day}/{dia_indicador.month} - Loja {loja}'
    #mail.Body = 'Message body'

    if faturamento_dia >= meta_faturamento_dia:
        cor_fat_dia = 'green'
    else:
        cor_fat_dia = 'red'
    if qtdeprodutos_dia >= meta_qtdeprodutos_dia:
        cor_qtde_dia = 'green'
    else:
        cor_qtde_dia = 'red'
    if ticket_medio_dia >= meta_ticketmedio_dia:
        cor_ticket_dia = 'green'
    else:
        cor_ticket_dia = 'red'
    if faturamento_ano >= meta_faturamento_ano:
        cor_fat_ano = 'green'
    else:
        cor_fat_ano = 'red'
    if qtdeprodutos_ano >= meta_qtdeprodutos_ano:
        cor_qtde_ano = 'green'
    else:
        cor_qtde_ano = 'red'
    if ticket_medio_ano >= meta_ticketmedio_ano:
        cor_ticket_ano = 'green'
    else:
        cor_ticket_ano = 'red'


    mail.HTMLBody = f'''
    <p>Bom dia, {nome}</p>
    <p>O resultado de ontem <strong>({dia_indicador.day}/{dia_indicador.month})</strong> da <strong>Loja {loja}<strong/> foi:</p>

    <table>
      <tr>
        <th>INDICADOR</th>
        <th>VALOR DIA</th>
        <th>META DIA</th>
        <th>CENÁRIO DIA</th>
      </tr>
      <tr>
        <td>Faturamento</td>
        <td style='text-align:center'>{faturamento_dia}</td>
        <td style='text-align:center'>{meta_faturamento_dia}</td>
        <td style='text-align:center'><font color="{cor_fat_dia}">◙</font></td>
      </tr>
      <tr>
        <td>Diversidade de Produtos</td>
        <td style='text-align:center'>{qtdeprodutos_dia}</td>
        <td style='text-align:center'>{meta_qtdeprodutos_dia}</td>
        <td style='text-align:center'><font color="{cor_qtde_dia}">◙</font></td>
      </tr>
      <tr>
        <td>Ticket Médio</td>
        <td style='text-align:center'>{ticket_medio_dia}</td>
        <td style='text-align:center'>{meta_ticketmedio_dia}</td>
        <td style='text-align:center'><font color="{cor_ticket_dia}">◙</font></td>
      </tr>
    </table>
    <br>
    <table>
      <tr>
        <th>INDICADOR</th>
        <th>VALOR DIA</th>
        <th>META DIA</th>
        <th>CENÁRIO DIA</th>
      </tr>
      <tr>
        <td>Faturamento</td>
        <td style='text-align:center'>{faturamento_ano}</td>
        <td style='text-align:center'>{meta_faturamento_ano}</td>
        <td style='text-align:center'><font color="{cor_fat_ano}">◙</font></td>
      </tr>
      <tr>
        <td>Diversidade de Produtos</td>
        <td style='text-align:center'>{qtdeprodutos_ano}</td>
        <td style='text-align:center'>{meta_qtdeprodutos_ano}</td>
        <td style='text-align:center'><font color="{cor_qtde_ano}">◙</font></td>
      </tr>
      <tr>
        <td>Ticket Médio</td>
        <td style='text-align:center'>{ticket_medio_ano}</td>
        <td style='text-align:center'>{meta_ticketmedio_ano}</td>
        <td style='text-align:center'><font color="{cor_ticket_ano}">◙</font></td>
      </tr>
    </table>

    <p>Segue me anexo planilha com todos os dados para mais detalhes.</p>
    <p>Qualquer dúvida, estou a disposição.</p>
    <p>Att.,</p>
    <p>Anderson F. S. de Oliveira</p>
    '''

    # To attach a file to the email (optional):
    attachment  = pathlib.Path.cwd() / caminho_backup / loja / f'{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx'
    mail.Attachments.Add(str(attachment))

    mail.Send()
    print(f'E-mail da loja {loja} enviado')

### Criar ranking para diretoria

In [13]:
faturamento_lojas_ano = vendas_df.groupby('Loja')[['Loja', 'Valor Final']].sum()
faturamento_lojas_ano = faturamento_lojas_ano.sort_values(by='Valor Final', ascending=False)
nome_arquivo = f'{dia_indicador.month}_{dia_indicador.day}_Ranking Anual.xlsx'
faturamento_lojas_ano.to_excel(r'Backup Arquivos Loja\{}'.format(nome_arquivo))
display(faturamento_lojas_ano)

vendas_dia = vendas_df.loc[vendas_df['Data']==dia_indicador, :]
faturamento_lojas_dia = vendas_dia.groupby('Loja')[['Loja', 'Valor Final']].sum()
faturamento_lojas_dia = faturamento_lojas_dia.sort_values(by='Valor Final', ascending=False)
nome_arquivo = f'{dia_indicador.month}_{dia_indicador.day}_Ranking Dia.xlsx'
faturamento_lojas_dia.to_excel(r'Backup Arquivos Loja\{}'.format(nome_arquivo))
display(faturamento_lojas_dia)

                                  Valor Final
Loja
Iguatemi Campinas                     1762419
Shopping Vila Velha                   1731167
Bourbon Shopping SP                   1726110
Rio Mar Recife                        1722766
Shopping SP Market                    1721763
Palladium Shopping Curitiba           1721120
Norte Shopping                        1711968
Ribeirão Shopping                     1707122
Iguatemi Esplanada                    1699681
Rio Mar Shopping Fortaleza            1698430
Shopping Center Leste Aricanduva      1682870
Novo Shopping Ribeirão Preto          1678225
Shopping Iguatemi Fortaleza           1674824
Center Shopping Uberlândia            1668921
Shopping União de Osasco              1663770
Shopping Barra                        1653103
Passei das Águas Shopping             1649014
Shopping Eldorado                     1648111
Salvador Shopping                     1646739
Shopping Center Interlagos            1640486
Shopping Ibirapuera                   1635060
Parque Dom Pedro Shopping             1631630
Shopping Recife                       1624879
Shopping Midway Mall                  1590441
Shopping Morumbi                      1586444

                                  Valor Final
Loja
Salvador Shopping                        3950
Novo Shopping Ribeirão Preto             3400
Center Shopping Uberlândia               2651
Shopping Eldorado                        2391
Shopping Center Interlagos               1582
Shopping Recife                          1366
Norte Shopping                           1259
Shopping União de Osasco                 1207
Shopping Vila Velha                       937
Bourbon Shopping SP                       676
Ribeirão Shopping                         650
Shopping Center Leste Aricanduva          485
Palladium Shopping Curitiba               381
Rio Mar Shopping Fortaleza                368
Shopping Midway Mall                      170
Shopping Ibirapuera                       118

### Enviar e-mail para diretoria (Outlook)

In [ ]:
#enviar email
outlook = win32.Dispatch('outlook.application')
mail = outlook.CreateItem(0)
mail.To = email_df.loc[email_df['Loja']=='Diretoria', 'E-mail'].values[0]
mail.Subject = f'Ranking Dia {dia_indicador.day}/{dia_indicador.month}'
mail.Body = f'''
      Presados, bom dia
   Segue em anexo os ranking's anuais e diários de todas as lojas, e abaixo os destaques:
   
Melhor loja do dia em Faturamento: Loja {faturamento_lojas_dia.index[0]} com Faturamento de R$ {faturamento_lojas_dia.iloc[0, 0]:.2f}
Pior loja do dia em Faturamento: Loja {faturamento_lojas_dia.index[-1]} com Faturamento de R$ {faturamento_lojas_dia.iloc[-1, 0]:.2f}

Melhor loja do ano em Faturamento: Loja {faturamento_lojas_ano.index[0]} com Faturamento de R$ {faturamento_lojas_ano.iloc[0, 0]:.2f}
Pior loja do ano em Faturamento: Loja {faturamento_lojas_ano.index[-1]} com Faturamento de R$ {faturamento_lojas_ano.iloc[-1, 0]:.2f}

Qualquer dúvida, estou a disposição.
Att.,
Anderson F. S. de Oliveira
'''

# To attach a file to the email (optional):
attachment  = pathlib.Path.cwd() / caminho_backup / f'{dia_indicador.month}_{dia_indicador.day}_Ranking Anual.xlsx'
mail.Attachments.Add(str(attachment))
attachment  = pathlib.Path.cwd() / caminho_backup / f'{dia_indicador.month}_{dia_indicador.day}_Ranking Dia.xlsx'
mail.Attachments.Add(str(attachment))

mail.Send()